/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.ChiTietPhieuNhapDAO;
import DAO.NguyenLieuDAO;
import DAO.NhaCungCapDAO;
import DAO.NhanVienDAO;
import DAO.PhieuNhapDAO;
import Model.ChiTietPhieuNhap;
import Model.NguyenLieu;
import Model.NhaCungCap;
import Model.NhanVien;
import Model.PhieuNhap;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Duyke
 */
public class QL_PhieuNhap extends javax.swing.JFrame {

    /**
     * Creates new form QL_PhieuNhap
     */
    public QL_PhieuNhap() {
        initComponents();
        setLocationRelativeTo(null);
        loadComboBox();
    }
    NhanVienDAO nvdao = new NhanVienDAO();
    NhaCungCapDAO nccdao = new NhaCungCapDAO();
    NguyenLieuDAO nldao = new NguyenLieuDAO();
    PhieuNhapDAO pndao = new PhieuNhapDAO();
    
    private void loadComboBox() {
        try {
            for (NhanVien nv : nvdao.getAll()) {
                cbMaNV.addItem(nv.getMaNV());
            }
            for (NhaCungCap ncc : nccdao.getAll()) {
                cbNCC.addItem(ncc.getMaNCC());
            }
            for (NguyenLieu nl : nldao.getAll()) {
                cbMaNL.addItem(nl.getMaNguyenLieu());
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Lỗi khi tải dữ liệu: " + e.toString());
        }
    }
    
    private String chuyenDonViTinh(String dvtTrongDB) {
        switch (dvtTrongDB.toLowerCase()) {
            case "gram":
                return "kilogram";
            case "ml":
                return "lít";
            case "cái":
            default:
                return "cái";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnQuayLại = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaPN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNgayNhap = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnTaoPN = new javax.swing.JButton();
        cbMaNV = new javax.swing.JComboBox<>();
        cbNCC = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTenNL = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnThemVaoBang = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnchinhsua = new javax.swing.JButton();
        cbDVT = new javax.swing.JComboBox<>();
        cbMaNL = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNguyenLieu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 153, 0));
        jLabel1.setText("PHIẾU NHẬP");

        btnQuayLại.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuayLại.setText("Quay Lại");
        btnQuayLại.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLạiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnQuayLại)
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnQuayLại)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Mã Phiếu Nhập");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Mã Nhân Viên");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Mã Nhà Cung Cấp");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Ngày Nhập");

        btnTaoPN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTaoPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Action-file-new-icon.png"))); // NOI18N
        btnTaoPN.setText("Tạo Phiếu Nhập Mới");
        btnTaoPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoPNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(btnTaoPN, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(btnTaoPN, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cbMaNV.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N

        cbNCC.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbNCC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbMaNV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaPN)
                    .addComponent(txtNgayNhap)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaPN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(cbNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Mã Nguyên Liệu");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Tên Nguyên Liệu");

        txtTenNL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTenNL.setForeground(new java.awt.Color(255, 102, 102));
        txtTenNL.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Đơn Vị Tính");

        txtSoLuong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Số Lượng");

        btnThemVaoBang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThemVaoBang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Actions-document-new-icon.png"))); // NOI18N
        btnThemVaoBang.setText("Thêm ");
        btnThemVaoBang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemVaoBangActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Action-cancel-icon.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnchinhsua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnchinhsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Actions-view-refresh-icon.png"))); // NOI18N
        btnchinhsua.setText("Chỉnh sửa");
        btnchinhsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchinhsuaActionPerformed(evt);
            }
        });

        cbDVT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbDVT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kilogram", "lít", "cái" }));

        cbMaNL.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        cbMaNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaNLActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Đơn Giá");

        txtDonGia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnThemVaoBang, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(btnchinhsua, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                            .addComponent(cbDVT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbMaNL, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTenNL, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbMaNL, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenNL, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbDVT, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel9))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThemVaoBang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnchinhsua, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Tổng Tiền");

        txtTongTien.setEditable(false);
        txtTongTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("VND");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(37, 37, 37))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblNguyenLieu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblNguyenLieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NL", "Tên NL", "DVT", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ));
        tblNguyenLieu.setToolTipText("");
        tblNguyenLieu.setRowHeight(30);
        tblNguyenLieu.setRowMargin(2);
        tblNguyenLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNguyenLieuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNguyenLieu);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void txtDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGiaActionPerformed

    private void btnThemVaoBangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemVaoBangActionPerformed
              try {
                if (txtTenNL.getText().trim().isEmpty()
                        || txtSoLuong.getText().trim().isEmpty()
                        || txtDonGia.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin !!");
                    return;
                }

                String soLuongStr = txtSoLuong.getText().trim();
                String donGiaStr = txtDonGia.getText().trim();

                // Kiểm tra soLuong là số dương
                double soLuongMoi;
                try {
                    soLuongMoi = Double.parseDouble(soLuongStr);
                    if (soLuongMoi <= 0) {
                        JOptionPane.showMessageDialog(null, "Số lượng phải là số dương.");
                        txtSoLuong.requestFocus();
                        return;
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Số lượng phải là số hợp lệ.");
                    txtSoLuong.requestFocus();
                    return;
                }

                // Kiểm tra donGia là số dương
                double donGiaMoi;
                try {
                    donGiaMoi = Double.parseDouble(donGiaStr);
                    if (donGiaMoi <= 0) {
                        JOptionPane.showMessageDialog(null, "Đơn giá phải là số dương.");
                        txtDonGia.requestFocus();
                        return;
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Đơn giá phải là số hợp lệ.");
                    txtDonGia.requestFocus();
                    return;
                }

                String maNL = (String) cbMaNL.getSelectedItem();
                String tenNL = txtTenNL.getText();
                String dvt = (String) cbDVT.getSelectedItem();

                double thanhTienMoi = soLuongMoi * donGiaMoi;

                DefaultTableModel model = (DefaultTableModel) tblNguyenLieu.getModel();
                boolean daTonTai = false;

                for (int i = 0; i < model.getRowCount(); i++) {
                    String maNLDaCo = model.getValueAt(i, 0).toString();
                    if (maNLDaCo.equals(maNL)) {
                        // Cộng dồn số lượng và tính lại thành tiền
                        double slCu = Double.parseDouble(model.getValueAt(i, 3).toString());
                        double dgCu = Double.parseDouble(model.getValueAt(i, 4).toString());

                        double slMoi = slCu + soLuongMoi;
                        double thanhTienMoi2 = slMoi * dgCu;

                        model.setValueAt(slMoi, i, 3); // Số lượng
                        model.setValueAt(thanhTienMoi2, i, 5); // Thành tiền
                        daTonTai = true;
                        break;
                    }
                }

                if (!daTonTai) {
                    model.addRow(new Object[]{maNL, tenNL, dvt, soLuongMoi, donGiaMoi, thanhTienMoi});
                }

                // Tính lại tổng tiền
                double tongTien = 0;
                for (int i = 0; i < model.getRowCount(); i++) {
                    tongTien += Double.parseDouble(model.getValueAt(i, 5).toString());
                }
                txtTongTien.setText(String.format("%.2f", tongTien));

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lỗi: " + e.toString());
            }
    }//GEN-LAST:event_btnThemVaoBangActionPerformed

    private void cbMaNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaNLActionPerformed
        try {
            String selectedMaNL = (String) cbMaNL.getSelectedItem();
            for (NguyenLieu nl : nldao.getAll()) {
                if (nl.getMaNguyenLieu().equals(selectedMaNL)) {
                    txtTenNL.setText(nl.getTenNguyenLieu());
                    String donViGoc = nl.getDVT();
                    cbDVT.removeAllItems();
                    cbDVT.addItem(chuyenDonViTinh(donViGoc));
                    txtSoLuong.setText("");
                    txtDonGia.setText("");
                    break;
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Lỗi khi tải dữ liệu: " + e.toString());
        }

    }//GEN-LAST:event_cbMaNLActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int selectedRow = tblNguyenLieu.getSelectedRow();
    
        if (selectedRow >= 0) {
            // Hiển thị hộp thoại xác nhận trước khi xóa
            int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có thực sự muốn xóa dòng này?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );

            // Nếu người dùng chọn YES, thì xóa dòng đã chọn
            if (confirm == JOptionPane.YES_OPTION) {
                ((DefaultTableModel) tblNguyenLieu.getModel()).removeRow(selectedRow);
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xóa.");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnchinhsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchinhsuaActionPerformed
        int selectedRow = tblNguyenLieu.getSelectedRow();
        if (selectedRow >= 0) {
            // Lấy giá trị từ các trường nhập liệu
            String maNL = cbMaNL.getSelectedItem().toString();
            String tenNL = txtTenNL.getText().trim();
            String dvt = cbDVT.getSelectedItem().toString();
            String soLuongStr = txtSoLuong.getText().trim();
            String donGiaStr = txtDonGia.getText().trim();

            // Kiểm tra dữ liệu nhập vào
            if (tenNL.isEmpty() || soLuongStr.isEmpty() || donGiaStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
                return;
            }

            // Kiểm tra số lượng và đơn giá phải là số hợp lệ
            double soLuong, donGia;
            try {
                soLuong = Double.parseDouble(soLuongStr);
                donGia = Double.parseDouble(donGiaStr);
                if (soLuong <= 0 || donGia <= 0) {
                    JOptionPane.showMessageDialog(this, "Số lượng và đơn giá phải là số dương!");
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Số lượng và đơn giá phải là số hợp lệ!");
                return;
            }

            // Tính lại thành tiền
            double thanhTien = soLuong * donGia;

            // Cập nhật lại dòng trong bảng
            DefaultTableModel model = (DefaultTableModel) tblNguyenLieu.getModel();
            model.setValueAt(tenNL, selectedRow, 1); // Cập nhật tên nguyên liệu
            model.setValueAt(dvt, selectedRow, 2); // Cập nhật đơn vị tính
            model.setValueAt(soLuong, selectedRow, 3); // Cập nhật số lượng
            model.setValueAt(donGia, selectedRow, 4); // Cập nhật đơn giá
            model.setValueAt(thanhTien, selectedRow, 5); // Cập nhật thành tiền

            JOptionPane.showMessageDialog(this, "Cập nhật sản phẩm thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm để chỉnh sửa!");
        }
    }//GEN-LAST:event_btnchinhsuaActionPerformed

    private void btnTaoPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoPNActionPerformed
        try {
            String maPN = txtMaPN.getText().trim();
            String maNV = (String) cbMaNV.getSelectedItem();
            String maNCC = (String) cbNCC.getSelectedItem();

            // Đọc ngày nhập
            String ngayNhapStr = txtNgayNhap.getText().trim();
            Date ngayNhap = null;
            
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                ngayNhap = sdf.parse(ngayNhapStr);
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(this, "Ngày nhập không hợp lệ! (Định dạng: dd/MM/yyyy)");
                return;
            }

            // Kiểm tra bảng nguyên liệu
            DefaultTableModel model = (DefaultTableModel) tblNguyenLieu.getModel();
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Chưa có nguyên liệu nào trong bảng!");
                return;
            }

            // Tính tổng tiền
            double tongTien = 0;
            for (int i = 0; i < model.getRowCount(); i++) {
                tongTien += Double.parseDouble(model.getValueAt(i, 5).toString());
            }

            // Tạo phiếu nhập
            PhieuNhap pn = new PhieuNhap(maPN, maNV,ngayNhap, maNCC, tongTien, "Chưa duyệt");
            
            if (pndao.insertPhieuNhap(pn)) {
                ChiTietPhieuNhapDAO ctpnDAO = new ChiTietPhieuNhapDAO();
                boolean allInserted = true;
                
                for (int i = 0; i < model.getRowCount(); i++) {
                    String maNL = model.getValueAt(i, 0).toString();
                    double soLuong = Double.parseDouble(model.getValueAt(i, 3).toString());
                    double donGia = Double.parseDouble(model.getValueAt(i, 4).toString());
                    double thanhTien = Double.parseDouble(model.getValueAt(i, 5).toString());
                    
                    ChiTietPhieuNhap ctpn = new ChiTietPhieuNhap(maPN, maNL, soLuong, donGia, thanhTien);
                    if (!ctpnDAO.insert(ctpn)) {
                        allInserted = false;
                        break;
                    }
                }
                
                if (allInserted) {
                    JOptionPane.showMessageDialog(this, "Tạo phiếu và chi tiết thành công!");
                    btnTaoPN.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Tạo phiếu thành công nhưng lỗi khi lưu chi tiết!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Tạo phiếu thất bại!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnTaoPNActionPerformed

    private void btnQuayLạiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLạiActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Bạn có muốn quay lại?",
            "Xác nhận",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (confirm == JOptionPane.YES_OPTION) {
            new TrangChuNhanVien().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnQuayLạiActionPerformed

    private void tblNguyenLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNguyenLieuMouseClicked
        int selectedRow = tblNguyenLieu.getSelectedRow();
        if (selectedRow >= 0) {
            // Lấy giá trị từ dòng đã chọn và hiển thị lên các trường nhập liệu
            String maNL = tblNguyenLieu.getValueAt(selectedRow, 0).toString();
            String tenNL = tblNguyenLieu.getValueAt(selectedRow, 1).toString();
            String dvt = tblNguyenLieu.getValueAt(selectedRow, 2).toString();
            String soLuong = tblNguyenLieu.getValueAt(selectedRow, 3).toString();
            String donGia = tblNguyenLieu.getValueAt(selectedRow, 4).toString();

            // Cập nhật các trường nhập liệu
            cbMaNL.setSelectedItem(maNL);
            txtTenNL.setText(tenNL);
            cbDVT.setSelectedItem(dvt);
            txtSoLuong.setText(soLuong);
            txtDonGia.setText(donGia);
        }
    }//GEN-LAST:event_tblNguyenLieuMouseClicked

    /**
     * @param args the 
     * command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_PhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_PhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_PhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_PhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_PhieuNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLại;
    private javax.swing.JButton btnTaoPN;
    private javax.swing.JButton btnThemVaoBang;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnchinhsua;
    private javax.swing.JComboBox<String> cbDVT;
    private javax.swing.JComboBox<String> cbMaNL;
    private javax.swing.JComboBox<String> cbMaNV;
    private javax.swing.JComboBox<String> cbNCC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNguyenLieu;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaPN;
    private javax.swing.JTextField txtNgayNhap;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenNL;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
